export const movies = [
  {
    id: 1,
    title: "Inception",
    image: "https://picsum.photos/seed/inception/300/450",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
  },
  {
    id: 2,
    title: "The Dark Knight",
    image: "https://picsum.photos/seed/darkknight/300/450",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
  },
  {
    id: 3,
    title: "Interstellar",
    image: "https://picsum.photos/seed/interstellar/300/450",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
  },
  {
    id: 4,
    title: "The Matrix",
    image: "https://picsum.photos/seed/matrix/300/450",
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
  },
  {
    id: 5,
    title: "Pulp Fiction",
    image: "https://picsum.photos/seed/pulp/300/450",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
  },
  {
    id: 6,
    title: "The Shawshank Redemption",
    image: "https://picsum.photos/seed/shawshank/300/450",
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
  },
  {
    id: 7,
    title: "The Godfather",
    image: "https://picsum.photos/seed/godfather/300/450",
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
  },
  {
    id: 8,
    title: "Forrest Gump",
    image: "https://picsum.photos/seed/forrest/300/450",
    description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
  },
  {
    id: 9,
    title: "Fight Club",
    image: "https://picsum.photos/seed/fightclub/300/450",
    description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.",
  },
  {
    id: 10,
    title: "The Lord of the Rings",
    image: "https://picsum.photos/seed/lotr/300/450",
    description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
  },
  {
    id: 11,
    title: "Gladiator",
    image: "https://picsum.photos/seed/gladiator/300/450",
    description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
  },
  {
    id: 12,
    title: "The Prestige",
    image: "https://picsum.photos/seed/prestige/300/450",
    description: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
  },
  {
    id: 13,
    title: "The Departed",
    image: "https://picsum.photos/seed/departed/300/450",
    description: "An undercover cop and a mole in the police force attempt to identify each other while infiltrating an Irish gang in South Boston.",
  },
  {
    id: 14,
    title: "Saving Private Ryan",
    image: "https://picsum.photos/seed/ryan/300/450",
    description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
  },
  {
    id: 15,
    title: "The Green Mile",
    image: "https://picsum.photos/seed/greenmile/300/450",
    description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
  },
  {
    id: 16,
    title: "Se7en",
    image: "https://picsum.photos/seed/seven/300/450",
    description: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
  },
  {
    id: 17,
    title: "The Silence of the Lambs",
    image: "https://picsum.photos/seed/silence/300/450",
    description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
  },
  {
    id: 18,
    title: "Schindler's List",
    image: "https://picsum.photos/seed/schindler/300/450",
    description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
  },
  {
    id: 19,
    title: "Braveheart",
    image: "https://picsum.photos/seed/braveheart/300/450",
    description: "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.",
  },
  {
    id: 20,
    title: "Joker",
    image: "https://picsum.photos/seed/joker/300/450",
    description: "A mentally troubled comedian embarks on a downward spiral that leads to the creation of an iconic villain.",
  },
];
